language: cpp
compiler: clang
before_install:
  - ./travis-ci/travis_install_packages.sh
  - ./travis-ci/travis_build_ninja.sh
  - ./travis-ci/travis_build_libcxx.sh
  - ./travis-ci/travis_build_boost.sh
  - git clone git://github.com/berkus/libsupport berkus/support
script: CC=/usr/bin/clang CXX=/usr/bin/clang++ cmake -G "Ninja" -DBUILD_TESTING=YES . && ninja && ctest
notifications:
  email: false
